<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
	<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
	<link href='https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons' rel="stylesheet">

	<title>Cassandra GUI</title>
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />

	<meta charset="UTF-8">

	<meta name="author" content="Adrian Chwiałkowski, AC Apps" />
	<link href='https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons' rel="stylesheet">
<!--	<link href="/css/lib/vuetify.min.css" rel="stylesheet">
-->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">
	<link rel="shortcut icon" type="image/png" href="/img/logo64.png"/>
	<link href="https://fonts.googleapis.com/css?family=Aldrich" rel="stylesheet">



<?php $this->displayExternalCss(); ?>
<?php $this->displayInternalCss(); ?>

<?php $this->displayExternalJs(); ?>
<?php $this->displayInternalJs(); ?>


	<style>
		html,body{
			height: 100%;
			width: 100%;
			margin: 0;
			padding: 0;
			font-family: 'Roboto', sans-serif;
		}

		#app{
			height: 100%;
			width: 100%;
		}
	</style>
</head>



<body class="<?php echo @$this->controller.@$this->action ?>">

<div id="app">
	<app></app>
</div>



<?php echo $this->layout()->content; ?>

<?php \App\Vue::include($this); ?>


</body>
</html>
